// constants.ts
export const GITHUB_API_BASE = "https://api.github.com";

export const PLACEHOLDER = {
  nodes: [
    { id: 'root', label: 'next-graph', type: 'root', description: 'GitHub Repository Root' },
    { id: 'app',  label: 'app/',       type: 'folder', path: 'app' },
    { id: 'components', label: 'components/', type: 'folder', path: 'app/components' },
    { id: 'lib',  label: 'lib/',       type: 'folder', path: 'app' },
    { id: 'public', label: 'public/', type: 'folder', path: 'public' },
    { id: 'page', label: 'page.tsx',  type: 'file', path: 'app/page.tsx', language: 'TypeScript', size: 8200 },
    { id: 'layout', label: 'layout.tsx', type: 'file', path: 'app/layout.tsx', language: 'TypeScript', size: 720 },
    { id: 'globals', label: 'globals.css', type: 'file', path: 'app/globals.css', language: 'CSS', size: 490 },
    { id: 'graph', label: 'GraphCanvas.tsx', type: 'file', path: 'app/page.tsx', language: 'TypeScript', size: 3400 },
    { id: 'search', label: 'SearchBar.tsx', type: 'file', path: 'app/page.tsx', language: 'TypeScript', size: 1200 },
    { id: 'utils', label: 'utils.ts', type: 'file', path: 'app/layoutUtils.ts', language: 'TypeScript', size: 900 },
    { id: 'logo', label: 'logo.svg', type: 'file', path: 'public/logo.svg', size: 220 },
    { id: 'favicon', label: 'favicon.ico', type: 'file', path: 'public/favicon.ico', size: 25900 },
    { id: 'pkg', label: 'package.json', type: 'dependency', path: 'package.json', size: 535 },
    { id: 'tsconfig', label: 'tsconfig.json', type: 'file', path: 'tsconfig.json', size: 670 },
    { id: 'nextcfg', label: 'next.config.ts', type: 'file', path: 'next.config.ts', language: 'TypeScript', size: 135 },
  ],
  edges: [
    { id: 'e1', source: 'root', target: 'app' },
    { id: 'e2', source: 'root', target: 'components' },
    { id: 'e3', source: 'root', target: 'lib' },
    { id: 'e4', source: 'root', target: 'public' },
    { id: 'e5', source: 'root', target: 'pkg' },
    { id: 'e6', source: 'root', target: 'tsconfig' },
    { id: 'e7', source: 'root', target: 'nextcfg' },
    { id: 'e8', source: 'app', target: 'page' },
    { id: 'e9', source: 'app', target: 'layout' },
    { id: 'e10', source: 'app', target: 'globals' },
    { id: 'e11', source: 'components', target: 'graph' },
    { id: 'e12', source: 'components', target: 'search' },
    { id: 'e13', source: 'lib', target: 'utils' },
    { id: 'e14', source: 'public', target: 'logo' },
    { id: 'e15', source: 'public', target: 'favicon' },
  ],
};
